### ISSUE TITLE
pageFunction is not a function

### ISSUE THREAD

**Issue by rixw** [apifytech/actor-crawler-cheerio#2]
I have forked this repo as I want to extend it to add cookie jar functionality. I am struggling though because of a really weird error I get when I run either locally or on the Apify platform. 

**Steps to reproduce**

Node version: 10.15.3

1. Clone the master branch of this repo
2. Run `npm install` to install node modules
3. Run `apify init` to create `apify.json`
4. Copy an INPUT.json from the Apify web interface and save as `apify_storage/key_value_stores/default/INPUT.json`
5. Run `apify run`

Alternatively...

1. Fork the master branch of this repo
2. Create a new Actor in the Apify UI
3. Set the source to be the forked repo and build
4. Create a task the *exact* same input settings as a working task running `apify/cheerio-scraper`
5. Save and run

**Expected result**

Crawl runs

**Actual result**

```
***:actor-crawler-cheerio ***$ apify run
Run: npm start

> actor-crawler-cheerio@1.0.0 start /Users/***/Projects/actor-crawler-cheerio
> node main.js

INFO: Configuring the Crawler.
User function threw an exception:
Error: Input parameter "pageFunction" is not a function!
    at Object.exports.evalPageFunctionOrThrow (/Users/***/Projects/actor-crawler-cheerio/src/tools.js:19:36)
    at new CrawlerSetup (/Users/***/Projects/actor-crawler-cheerio/src/crawler_setup.js:64:41)
    at Apify.main (/Users/***/Projects/actor-crawler-cheerio/src/actor.js:18:19)
```

Stepping through this with the debugger, this line is the issue:

```
func = vm.runInThisContext(funcString);
```

I'd expect this to return a function, it doesn't, it returns `undefined` and for the life of me I can't figure out why.

**Comment by rixw** [comment]
Scratch this, I've realised I'm in the wrong repo, sorry.
